export { FleetIdentifierSchema, parseFleetIdentifier } from "./src/identifier";
export { issueBranchName } from "./src/issue-branch";
export {
  DEFAULT_PORT,
  ATLAS_FILENAME,
  FleetShipConfigSchema,
  type FleetShipConfig,
  AtlasSchema,
  type Atlas,
  AgentBridgeCredentialSchema,
  type AgentBridgeCredential,
} from "./src/config";
export {
  WorkspaceSummarySchema,
  WorkspaceStatusSchema,
  WorkspaceDiffSchema,
  WorkspaceRefsSchema,
  AgentStatusSchema,
  CreateWorkspaceRequestSchema,
  EphemeralWorkspaceSchema,
  AGENT_STATES,
  EPHEMERAL_CLEANUP_STATES,
  MAX_BLOCKED_REASON_LENGTH,
  type WorkspaceSummary,
} from "./src/workspace";
export type {
  EphemeralWorkspace,
  EphemeralCleanupState,
  WorkspaceDiff,
  WorkspaceRefs,
  WorkspaceStatus,
  AgentStatus,
  AgentState,
  UpdateAgentStatusRequest,
  CreateWorkspaceRequest,
  SwitchBranchRequest,
} from "./src/workspace";
export type { SystemResources } from "./src/system";
export { RepoSchema, CreateRepoInputSchema, type Repo, type CreateRepoInput } from "./src/repo";
export { ShipSchema, type Ship } from "./src/ship";
export {
  RoleSchema,
  UsernameSchema,
  PasswordSchema,
  EmailSchema,
  UserSchema,
  LoginRequestSchema,
  LoginResponseSchema,
  CreateUserRequestSchema,
  SetPasswordRequestSchema,
  SetEmailRequestSchema,
  SetRoleRequestSchema,
  WsTicketResponseSchema,
  type Role,
  type User,
  type LoginRequest,
  type LoginResponse,
  type CreateUserRequest,
  type SetPasswordRequest,
  type SetEmailRequest,
  type SetRoleRequest,
  type WsTicketResponse,
} from "./src/auth";
export {
  ARMORY_SECTIONS,
  ARMORY_DIRECTORY,
  DOTFILE_MAP_FILENAME,
  isSafeArmoryPath,
  ArmoryEntrySchema,
  DotfileMapSchema,
  ArmoryManifestSchema,
  ArmoryFileSchema,
  ArmorySyncRequestSchema,
  ArmorySyncStateSchema,
  ArmoryInstallSummarySchema,
  type ArmorySection,
  type ArmoryEntry,
  type DotfileMap,
  type ArmoryManifest,
  type ArmoryFile,
  type ArmorySyncRequest,
  type ArmorySyncState,
  type ArmoryInstallSummary,
} from "./src/armory";

export {
  SyncEventSchema,
  WorkspaceCreatedEventSchema,
  WorkspaceBranchChangedEventSchema,
  WorkspaceActivatedEventSchema,
  WorkspaceDeactivatedEventSchema,
  WorkspaceAgentStatusChangedEventSchema,
  WorkspaceRemovedEventSchema,
  FleetEventSchema,
  decodeFleetEvent,
  type SyncEvent,
  type FleetEvent,
} from "./src/events";
