/** Server-side entry: pulls in bun-vt. Browser code must import `webterm/protocol` instead. */

export {
  TerminalBridge,
  type TerminalBridgeOptions,
  FrameSequencer,
  type FrameSequencerOptions,
  type FrameDecision,
} from "./server";
export { serializeGrid, encodeCell, diffGrid } from "./encode";

export {
  ATTR,
  UNDERLINE,
  WIDTH,
  MIN_TERMINAL_COLS,
  MAX_TERMINAL_COLS,
  MIN_TERMINAL_ROWS,
  MAX_TERMINAL_ROWS,
  MAX_INPUT_BYTES,
  MAX_PENDING_BYTES,
  MAX_CLIENT_FRAME_BYTES,
  INVALID_MESSAGE_CLOSE_CODE,
  INVALID_MESSAGE_CLOSE_REASON,
  BINARY_MESSAGE_CLOSE_CODE,
  BINARY_MESSAGE_CLOSE_REASON,
  BUFFER_LIMIT_CLOSE_CODE,
  BUFFER_LIMIT_CLOSE_REASON,
  TERMINAL_CONFLICT_CLOSE_CODE,
  TERMINAL_CONFLICT_CLOSE_REASON,
  TERMINAL_TAKEOVER_CLOSE_CODE,
  TERMINAL_TAKEOVER_CLOSE_REASON,
  TERMINAL_TAKEOVER_QUERY,
  decodeClientMessage,
  decodeServerMessage,
  applyPatch,
  GridStream,
  type GridStreamResult,
  utf8ByteLength,
  clampTerminalSize,
  splitInput,
  type ClientMsg,
  type InitMsg,
  type InputMsg,
  type ResizeMsg,
  type AckMsg,
  type ResyncMsg,
  type ServerMsg,
  type GridMsg,
  type PatchMsg,
  type PatchRun,
  type ExitMsg,
  type WireCursor,
  type WireCursorShape,
  type WireCell,
  type WireCellObject,
  type WireColor,
} from "./protocol";
